- src/glyf.rs
If `Some(offcurve1), Some(offcurve2)` happens `last_offcurve` will be altered so on the next it won't be matched for sure and if it don't it certainly breaks leaving no need for `loop {}` AFAICS.
> [glyf] Simplify points to contour logic

- CHANGELOG.md
- c-api/lib.rs
- c-api/ttfparser.h
- src/lib.rs
- src/tables/os2.rs
- src/tables/post.rs
This adds functions to extract a few more useful metrics:
- methods to get the font's `cap_height` and `italic_angle`
- an `is_monospaced` method (which fixes #17)
- three more methods to get the typo ascender, descender and line gap independently from `use_typo_metrics` (this would be useful to me because in one project I always want to use the typo metrics and not sometimes this or that depending on how the font is configured).
If you have any feedback, I'd be happy to incorporate it! I did not write any tests for this because I also didn't see tests for similarly simple table parsing stuff.
> Extract more metrics from Post and OS/2 table

- CHANGELOG.md
- src/tables/cmap/format0.rs
For format 0, the parser would return glyph ID 0 instead of None even though (at least I think) zero means unmapped for this table (as it has fixed size and otherwise couldn't support fonts with less than 256 mappings).
> (cmap) Don't return glyph ID `0` instead of `None` for format 0.

- CHANGELOG.md
- src/tables/cmap/format2.rs
For format 2, there was a `>` comparison with an exclusive range end which should have been `>=` as far as I can tell. This could lead to a codepoint being mapped to a glyph when it was in fact unmapped.
> (cmap) Fix invalid mapping for format 2.

- CHANGELOG.md
- src/tables/cmap/format0.rs
- src/tables/cmap/format10.rs
- src/tables/cmap/format12.rs
- src/tables/cmap/format13.rs
- src/tables/cmap/format2.rs
- src/tables/cmap/format4.rs
- src/tables/cmap/format6.rs
- src/tables/cmap/mod.rs
I implemented reading all codepoints from a subtable through `Subtable::codepoints` as laid out in #20.
As discussed, this only parses the codepoints and not the glyph indices. Normally, instead of returning glyph ID `0`, the parsing methods return `None`. Since the codepoint-methods don't know about the glyph indices, calling `glyph_index` on a collected codepoint may now still return `None`. But I think that isn't too bad since a user can still check whether `glyph_index` returns `None` for each collected codepoint if necessary.
There is one exception to this rule for format 0 because otherwise we would always return all codepoints from `0` to `255` even though some of them may definitely be unmapped (aka mapped to zero).
While implementing format 0 and format 2 I noticed two things …
> Codepoints (fixes #20)

- src/tables/cff/cff1.rs
Saw the comment about 228/zcaron and set out to find an explanation. The reason is that the ISO Adobe charset only defines string ids up to 228 (p. 47 of [CFF Spec](https://wwwimages2.adobe.com/content/dam/acom/en/devnet/font/pdfs/5176.CFF.pdf)). Then the `<` stood out to me as it seems like 228 is valid too. Confirmed this by checking Harfbuzz:
https://github.com/harfbuzz/harfbuzz/blob/c8c5e52aba904cfede1c7e8e1043a392053938e6/src/hb-ot-cff1-table.hh#L1166
> Fix edge case in seac_code_to_glyph_id and clarify behaviour

- src/lib.rs
This enables support for custom font table providers, which is necessary if you want to decode the font tables in some way before handing them to ttf-parser (i.e.: gzip decoding / brotli decoding, etc.). 
Due to the `Deref` trait impls, this changes nothing about the public API - all methods that were previously available on the `Font` struct are now available on the `ParsedFaceTables` struct, too.
> Split out font table parsing into separate struct

- src/tables/cmap/mod.rs
Without this change, Face::glyph_index would not work for fonts with format 13 cmap subtables. This is commonly used for last resort fonts (e.g. https://github.com/unicode-org/last-resort-font).
> Adds support for format 13 subtables to cmap::Subtable::is_unicode.

- src/ggg.rs
- src/lib.rs
- src/tables/cmap/mod.rs
- src/tables/gdef.rs
- src/tables/os2.rs
This is more than what I require, but I think all make sense *unless* there is a chance they may have incompatible fields such as `f32` in the future.
Since the PR to `fontdb` will depend on this and it's non-breaking, I marked this as a release (didn't check whether anything else needs adding to the changelog).
> 0.12.1: prepare extra derives

- src/tables/svg.rs
The SVG document record offset for a document is with respect to the beginning of the SVGDocumentList and not with respect to the table as mentioned here 
https://docs.microsoft.com/en-us/typography/opentype/spec/svg
> Svg document records index fix(doc_list_offset was not considered)

- README.md
- Add `COLR/CPAL` tables
- FreeType 2.10.0 support `COLR/CPAL` tables
- FreeType 2.11.0 support `COLR` table v1 ([COLRv1](https://caniuse.com/colr-v1))
- [FreeType 2.12.0](https://github.com/freetype/freetype/commit/21d0fa374200aecc6605daf034a47167ea82ed6f) support `SVG` table(OT-SVG)
> FreeType now handles OT-SVG fonts, to be controlled with
FT_CONFIG_OPTION_SVG configuration macro. By default, it can
only load the 'SVG ' table of an OpenType font. However, by using
the svg-hooks property of the new 'ot-svg' module it is possible
to register an external SVG rendering engine. The FreeType demo
programs have been set up to use 'librsvg' as the rendering
library.
> docs: add COLR/CPAL table and update FreeType information

- src/parser.rs
- src/tables/ankr.rs
- src/tables/math.rs
This lets math subtables be `None` instead of attempting to read at an offset of `0`. As discussed in #110. It also moves the `read_at_offset32` to a private stream extension for the `ankr` table as discussed. While this doesn't fully resolve the offset problem, it at least fixes the specific bug in the math table.
> Handle null offsets in MATH table

- src/tables/cff/cff1.rs
When embedding a CIDFont in PDF, CIDs must be used in place of GIDs. Most fonts have an identity mapping, but some don't (mostly CJK ones). For those, the mapping is stored as the charset, but SIDs represent CIDs. From the CFF spec:
> The charset data, although in the same format as non-CIDFonts, will represent CIDs rather than SIDs,  [...]
Right now, the GID -> SID functionality in the CFF table is internal to `glyph_name`, which returns a string (which is `None` in this case because there are now actual strings for the "fake" SIDs). It would be great to have an exposed to way to extract the mapping with ttf-parser. I attached one possible way to expose this (open to suggestions for a better API). I opted for specifically calling this `glyph_cid` instead of something like `gid_to_sid` …
> Expose conversion from glyph ID to CID

- CHANGELOG.md
- README.md
- src/lib.rs
- src/tables/colr.rs
- src/tables/cpal.rs
- src/tables/mod.rs
This PR adds support for version 0 of the COLR and CPAL tables (#69). Version 0 is very simple in comparison to version 1: A color glyph is defined as a list of overlayed outline glyphs, each with a solid color.
The implementation is also pretty simple, the biggest question is the API design: Since a version 0 color glyph is conceptually really just a list of `(GlyphId, Color)`, an iterator based design would be possible. 
However, such an API design wouldn't accomodate version 1 down the road at all. For this reason, I decided to instead add a `ColorGlyphPainter` trait akin to the `OutlineBuilder` trait (I'm open for alternative naming suggestions). Currently, it only has a single method for painting an outline glyph in a color, but down the road it could be extended to accomodate other …
> Add support for COLR/CPAL v0

- examples/font2svg.rs
- src/lib.rs
- src/tables/svg.rs
A single svg document can be used to represent multiple glyphs, return the covered range with the data.
> return the svg document include the svg data and the covered range 

- src/lib.rs
- src/tables/os2.rs
After referencing [this Microsoft `fsType` specification](https://learn.microsoft.com/en-us/typography/opentype/spec/os2#fst), I noticed an inconsistency in the functions `{Face, os2::Table}::is_bitmap_embedding_allowed` which seemed to have an inverted interpretation of the flag's meaning. The checked flag, if set, really means "is embed *required* to be bitmap". Since that name isn't very clear either, I inverted the name to `is_outline_embedding_allowed` while keeping the logical return value unflipped.
Further, the specification allows much leniency for earlier versions of the OS/2 table, this PR adjusts the logic of `os2::Table::{permissions, is_subsetting_allowed, is_outline_embedding_allowed}` to take advantage of this to be as lenient as allowable for embeds.
After these changes, …
> Flip misnamed `is_bitmap_embedding_allowed` function, increase lenience of embed permissions for older OS/2 versions

- src/lib.rs
- src/tables/gvar.rs
I was reading through the code and had to check what `try_for_opt!` did. I factored the macro into built-in option methods to improve my comprehension of the code. I recognize this is a minor refactor that wasn't requested; please feel free to close this PR if it's too minor or it decreases readability.
In any case, thanks for writing `ttf-parser`! I'm enjoying using it.
> minor refactor: use built-in option methods instead of `try_for_opt!` macro

- src/tables/cff/cff1.rs
- src/tables/cff/charset.rs
So, I'm not entirely sure if this is how it's supposed to be resolved. I was using `ttf-parser` as a fuzzer for my subsetter, and realized that `parse_charset` has this check to return `None` when there is only one glyph (i.e. the .notdef glyph) in the font. This means that it will fail to parse the cff table in that case. However, I would argue that a font with just the .notdef glyph should be perfectly fine in theory (even though in practice this obviously doesn't make a lot of sense), because the `.notdef` glyph can have outlines as well.
> Fix check in parse_charset

- src/tables/gvar.rs
Right now, the whole outline building process is aborted if we encounter a glypg with no outline data in `gvar`. In `glyf`, we just ignore  the single component glyph if it has no empty data. I think the latter is the right behavior and also seems to be what `fontations` does.
> Fix behaviour in component glyph in gvar

- src/ggg/chained_context.rs
- src/ggg/mod.rs
So I was facing problems with a new font added in harfbuzz, and turns out that the reason was that a specific GSUB lookup failed to parse properly. After looking at the spec, I noticed the following:
Offsets cann be NULL, which wasn't checked for in our implementation. This is the least invasive approach I could think of (requires no changes in rustybuzz), and the test case passes now as well, so I hope it's okay.
> Fix treating null offsets as error in GSUB

- .github/workflows/main.yml
- Cargo.toml
- examples/font2svg.rs
- src/lib.rs
- src/tables/colr.rs
- tests/tables/colr.rs
Will make it easier to port code from harfbuzz to rustybuzz. I hope I did the `libm` thing correctly.
> Simplify COLR API for transforms

- .github/workflows/main.yml
- Cargo.toml
- src/lib.rs
So what I did here is that I always include the `core_maths` dependency and I removed `no-std-float`, so that in order to enable `no_std` mode, you can simply disable all default features and don't need to additionally enable a separate feature. The reason for this is that since features are additive, it's apparently [bad practice to have an explicity `no_std` feature.](https://www.reddit.com/r/rust/comments/f2fsi8/comment/fhcji58). Because if one crate depends on `std` of `ttf-parser` and another on `no-std-float`, then both features would be activated if a crates uses both of them as a dependency.
If you want I can undo the last part, though.
> Use core maths

- README.md
- examples/font-info.rs
- src/lib.rs
- src/tables/mod.rs
- src/tables/stat.rs
https://learn.microsoft.com/en-us/typography/opentype/spec/stat
This PR adds support for parsing the `STAT` table and its related data types.  It's a pretty simple table but as in #87 the issues of testing and API design deserve some consideration.
Additionally, should this be placed behind a feature?
> Add support for the STAT table.

- c-api/Cargo.toml
- c-api/README.md
I added the metadata and hopefully this time the README update is what you had in mind.
> Add cargo-c metadata

- src/lib.rs
- src/tables/avar.rs
There is an issue in Rustybuzz where calling `set_variations` which internally calls `set_variation` multiple time will cause the avar table to be applied to the same coordinate value multiple times. This causes the wrong values to be set.
This is an attempt at a fix that by only applying the avar table to the coordinate currently being set.
Fixes RazrFalcon/rustybuzz#136
> Fix: Only apply avar table to the variation axis being set

- .github/workflows/main.yml
- Cargo.toml
1.63.0 is the MSVR of the libm crate version used in our manifest and seems to be the current lowest common denominator. It is only used when building no-std, but I don't see any documentation that the MSVR for this project can/should be separate for default features vs. non-default features.
> Document change to MSRV

- Cargo.toml
As a follow up to @waywardmonkeys recent commit fixing typos, this configures the tool `typos` such that it can be used out of the box without producing false positives.
> Configure typos

- src/tables/colr.rs
- tests/tables/colr.rs
Necessary for getting the proper glyph extents in rustybuzz, and [matches HarfBuzz](https://github.com/harfbuzz/harfbuzz/blob/92af2e47fc88a960172367e8a53262d2bab17a51/src/OT/Color/COLR/COLR.hh#L2747-L2753).
We can't solve this solely in rustybuzz by just checking if the COLR table is v0 and behaving differently if so, because we can have COLRv0 glyphs in a COLRv1 table.
> Call push_clip() and pop_clip() when painting COLRv0 glyphs

- Cargo.toml
This is a parallel to https://github.com/harfbuzz/rustybuzz/pull/153 and comments should probably be pursued there.
The only differences are:
* This crate has very few and relatively slow moving depnedencies, so it is less of an issue.
* This project doesn't track a lock file (yet). We could certainly start doing there is a need to do so, but it could factor in to regression testing when not having patch-level pinned dependencies in the manifest.
> Relax dependency pinning from patch to minor level only

- Cargo.toml
During our dependency reviews we discovered that the ttf-parser crate as uploaded to crates.io includes test data and additional tools that are not used by the rust code. This increases the package size and makes it harder to review the source code.
This commit explicitly includes only relevant files. This helps to reduce the package size
Before: 118 files, 1.0MiB (198.4KiB compressed)
After: 75 files, 747.1KiB (140.6KiB compressed)
Overall based on the reduction in the compressed package size and the current download numbers that results to a traffic reduction for crates.io of around 110GB / Month.
> Exclude test data and tools from published packages
